"""make migrations

Revision ID: 0c6baaec2c8d
Revises: 6f5ccdbbe42e
Create Date: 2024-02-01 08:57:29.144187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6baaec2c8d'
down_revision = '6f5ccdbbe42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('invoice_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'invoice_number')
    # ### end Alembic commands ###
