"""make migration

Revision ID: a2d2f283bea8
Revises: 
Create Date: 2023-08-30 13:49:20.744928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d2f283bea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UserAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=500), nullable=True),
    sa.Column('Email', sa.String(length=500), nullable=True),
    sa.Column('Password', sa.String(length=500), nullable=True),
    sa.Column('Mobile', sa.String(length=120), nullable=True),
    sa.Column('verification_token', sa.String(length=1120), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('Member', sa.Boolean(), nullable=True),
    sa.Column('Membership_Type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('UserAccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserAccount_Email'), ['Email'], unique=True)
        batch_op.create_index(batch_op.f('ix_UserAccount_Mobile'), ['Mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserAccount_Password'), ['Password'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserAccount_User'), ['User'], unique=False)

    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=500), nullable=True),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.Column('Start_Facility', sa.String(length=500), nullable=True),
    sa.Column('End_Facility', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facility_Capacity'), ['Capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_facility_End_Facility'), ['End_Facility'], unique=False)
        batch_op.create_index(batch_op.f('ix_facility_Name'), ['Name'], unique=False)
        batch_op.create_index(batch_op.f('ix_facility_Start_Facility'), ['Start_Facility'], unique=False)

    op.create_table('Sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Start_time', sa.Time(), nullable=True),
    sa.Column('End_time', sa.Time(), nullable=True),
    sa.Column('Remaining_Cap', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Sessions_Date'), ['Date'], unique=False)
        batch_op.create_index(batch_op.f('ix_Sessions_End_time'), ['End_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_Sessions_Remaining_Cap'), ['Remaining_Cap'], unique=False)
        batch_op.create_index(batch_op.f('ix_Sessions_Start_time'), ['Start_time'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('Activity_Name', sa.String(length=500), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_Activity_Name'), ['Activity_Name'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_Amount'), ['Amount'], unique=False)

    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_Amount'), ['Amount'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], )
    )
    op.create_table('Booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Book_Time', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('Size', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Booking_Amount'), ['Amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_Booking_Book_Time'), ['Book_Time'], unique=False)
        batch_op.create_index(batch_op.f('ix_Booking_Size'), ['Size'], unique=False)
        batch_op.create_index(batch_op.f('ix_Booking_Status'), ['Status'], unique=False)

    op.create_table('session_activity',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id'], ),
    sa.UniqueConstraint('session_id', 'activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_activity')
    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Booking_Status'))
        batch_op.drop_index(batch_op.f('ix_Booking_Size'))
        batch_op.drop_index(batch_op.f('ix_Booking_Book_Time'))
        batch_op.drop_index(batch_op.f('ix_Booking_Amount'))

    op.drop_table('Booking')
    op.drop_table('user_role')
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_Amount'))

    op.drop_table('receipt')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_Amount'))
        batch_op.drop_index(batch_op.f('ix_activity_Activity_Name'))

    op.drop_table('activity')
    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Sessions_Start_time'))
        batch_op.drop_index(batch_op.f('ix_Sessions_Remaining_Cap'))
        batch_op.drop_index(batch_op.f('ix_Sessions_End_time'))
        batch_op.drop_index(batch_op.f('ix_Sessions_Date'))

    op.drop_table('Sessions')
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facility_Start_Facility'))
        batch_op.drop_index(batch_op.f('ix_facility_Name'))
        batch_op.drop_index(batch_op.f('ix_facility_End_Facility'))
        batch_op.drop_index(batch_op.f('ix_facility_Capacity'))

    op.drop_table('facility')
    with op.batch_alter_table('UserAccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserAccount_User'))
        batch_op.drop_index(batch_op.f('ix_UserAccount_Password'))
        batch_op.drop_index(batch_op.f('ix_UserAccount_Mobile'))
        batch_op.drop_index(batch_op.f('ix_UserAccount_Email'))

    op.drop_table('UserAccount')
    op.drop_table('Role')
    # ### end Alembic commands ###
