"""make migrations

Revision ID: b4dd2fa7ae1e
Revises: 
Create Date: 2023-12-19 15:03:12.778102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dd2fa7ae1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UserAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=500), nullable=True),
    sa.Column('Email', sa.String(length=500), nullable=True),
    sa.Column('Password', sa.String(length=500), nullable=True),
    sa.Column('Mobile', sa.String(length=120), nullable=True),
    sa.Column('verification_token', sa.String(length=1120), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('Member', sa.Boolean(), nullable=True),
    sa.Column('member_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_UserAccount_Email'), 'UserAccount', ['Email'], unique=True)
    op.create_index(op.f('ix_UserAccount_Mobile'), 'UserAccount', ['Mobile'], unique=False)
    op.create_index(op.f('ix_UserAccount_Password'), 'UserAccount', ['Password'], unique=False)
    op.create_index(op.f('ix_UserAccount_User'), 'UserAccount', ['User'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=500), nullable=True),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.Column('Start_Facility', sa.String(length=500), nullable=True),
    sa.Column('End_Facility', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_Capacity'), 'facility', ['Capacity'], unique=False)
    op.create_index(op.f('ix_facility_End_Facility'), 'facility', ['End_Facility'], unique=False)
    op.create_index(op.f('ix_facility_Name'), 'facility', ['Name'], unique=False)
    op.create_index(op.f('ix_facility_Start_Facility'), 'facility', ['Start_Facility'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('interval', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_name'), 'membership', ['name'], unique=False)
    op.create_table('Sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Start_time', sa.Time(), nullable=True),
    sa.Column('End_time', sa.Time(), nullable=True),
    sa.Column('Remaining_Cap', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sessions_Date'), 'Sessions', ['Date'], unique=False)
    op.create_index(op.f('ix_Sessions_End_time'), 'Sessions', ['End_time'], unique=False)
    op.create_index(op.f('ix_Sessions_Remaining_Cap'), 'Sessions', ['Remaining_Cap'], unique=False)
    op.create_index(op.f('ix_Sessions_Start_time'), 'Sessions', ['Start_time'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('Activity_Name', sa.String(length=500), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_Activity_Name'), 'activity', ['Activity_Name'], unique=False)
    op.create_index(op.f('ix_activity_Amount'), 'activity', ['Amount'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_Amount'), 'receipt', ['Amount'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], )
    )
    op.create_table('Booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('Book_Time', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('Size', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Booking_Amount'), 'Booking', ['Amount'], unique=False)
    op.create_index(op.f('ix_Booking_Book_Time'), 'Booking', ['Book_Time'], unique=False)
    op.create_index(op.f('ix_Booking_Size'), 'Booking', ['Size'], unique=False)
    op.create_index(op.f('ix_Booking_Status'), 'Booking', ['Status'], unique=False)
    op.create_table('session_activity',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id'], ),
    sa.UniqueConstraint('session_id', 'activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_activity')
    op.drop_index(op.f('ix_Booking_Status'), table_name='Booking')
    op.drop_index(op.f('ix_Booking_Size'), table_name='Booking')
    op.drop_index(op.f('ix_Booking_Book_Time'), table_name='Booking')
    op.drop_index(op.f('ix_Booking_Amount'), table_name='Booking')
    op.drop_table('Booking')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_receipt_Amount'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_activity_Amount'), table_name='activity')
    op.drop_index(op.f('ix_activity_Activity_Name'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_Sessions_Start_time'), table_name='Sessions')
    op.drop_index(op.f('ix_Sessions_Remaining_Cap'), table_name='Sessions')
    op.drop_index(op.f('ix_Sessions_End_time'), table_name='Sessions')
    op.drop_index(op.f('ix_Sessions_Date'), table_name='Sessions')
    op.drop_table('Sessions')
    op.drop_index(op.f('ix_membership_name'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_facility_Start_Facility'), table_name='facility')
    op.drop_index(op.f('ix_facility_Name'), table_name='facility')
    op.drop_index(op.f('ix_facility_End_Facility'), table_name='facility')
    op.drop_index(op.f('ix_facility_Capacity'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_UserAccount_User'), table_name='UserAccount')
    op.drop_index(op.f('ix_UserAccount_Password'), table_name='UserAccount')
    op.drop_index(op.f('ix_UserAccount_Mobile'), table_name='UserAccount')
    op.drop_index(op.f('ix_UserAccount_Email'), table_name='UserAccount')
    op.drop_table('UserAccount')
    op.drop_table('Role')
    # ### end Alembic commands ###
