"""make migrations

Revision ID: d195b8a5fdcd
Revises: c1369f723a32
Create Date: 2024-01-06 16:47:40.349966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd195b8a5fdcd'
down_revision = 'c1369f723a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserAccount', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserAccount', 'profile_picture')
    # ### end Alembic commands ###
